name: CI

on:
  push:
    branches:
      - dev
      - "feat/**" # Feature 브랜치 패턴

# 1. test
# 2. PR
jobs: 
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v4

      - name: Install Deps
        run: npm install

      - name: Run Test
        run: npm run test

      - name: Run Build
        run: npm run build