name: CI

on:
  push:
    branches:
      - dev
      - "feat/**"

# 1. test
# 2. PR
env:
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
jobs: 
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v4

      - name: Install Deps
        run: npm install

      - name: Run Test
        run: npm run test

      - name: Run Build
        run: npm run build

  create-pr:
    needs: run-test
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v4

      - name: create pr
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore: create pr test"
          body: "this is a test pr"
          base: main
          branch: ${{ github.ref }}
